dist: trusty

matrix:
  include:
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-4.8" CXX_STANDARD=11
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'ppa:mhier/libboost-latest'
        packages:
        - g++-4.8
        - boost1.70
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-4.9" CXX_STANDARD=11
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'ppa:mhier/libboost-latest'
        packages:
        - g++-4.9
        - boost1.70
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-5" CXX_STANDARD=11
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'ppa:mhier/libboost-latest'
        packages:
        - g++-5
        - boost1.70
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-6" CXX_STANDARD=11
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'ppa:mhier/libboost-latest'
        packages:
        - g++-6
        - boost1.70
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-7" CXX_STANDARD=11
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'ppa:mhier/libboost-latest'
        packages:
        - g++-7
        - boost1.70
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-8" CXX_STANDARD=11
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'ppa:mhier/libboost-latest'
        packages:
        - g++-8
        - boost1.70
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-8" CXX_STANDARD=11 TOML_HEAD=ON
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'ppa:mhier/libboost-latest'
        packages:
        - g++-8
        - boost1.70
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-8" CXX_STANDARD=14
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'ppa:mhier/libboost-latest'
        packages:
        - g++-8
        - boost1.70
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-8" CXX_STANDARD=17
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'ppa:mhier/libboost-latest'
        packages:
        - g++-8
        - boost1.70
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-8" CXX_STANDARD=17 TOML_HEAD=ON
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'ppa:mhier/libboost-latest'
        packages:
        - g++-8
        - boost1.70
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-3.9" CXX_STANDARD=11
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'ppa:mhier/libboost-latest'
        - llvm-toolchain-trusty-3.9
        packages:
        - g++-8
        - clang-3.9
        - boost1.70
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-4.0" CXX_STANDARD=11
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'ppa:mhier/libboost-latest'
        - llvm-toolchain-trusty-4.0
        packages:
        - g++-8
        - clang-4.0
        - boost1.70
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-5.0" CXX_STANDARD=11
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'ppa:mhier/libboost-latest'
        - llvm-toolchain-trusty-5.0
        packages:
        - g++-8
        - clang-5.0
        - boost1.70
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-6.0" CXX_STANDARD=11
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'ppa:mhier/libboost-latest'
        - llvm-toolchain-trusty-6.0
        packages:
        - g++-8
        - clang-6.0
        - boost1.70
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-7" CXX_STANDARD=11
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'ppa:mhier/libboost-latest'
        - llvm-toolchain-trusty-7
        packages:
        - g++-8
        - clang-7
        - boost1.70
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-8" CXX_STANDARD=11
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'ppa:mhier/libboost-latest'
        - llvm-toolchain-trusty-8
        packages:
        - g++-8
        - clang-8
        - boost1.70
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-8" CXX_STANDARD=11 TOML_HEAD=ON
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'ppa:mhier/libboost-latest'
        - llvm-toolchain-trusty-8
        packages:
        - g++-8
        - clang-8
        - boost1.70
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-8" CXX_STANDARD=14
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'ppa:mhier/libboost-latest'
        - llvm-toolchain-trusty-8
        packages:
        - clang-8
        - g++-8
        - boost1.70
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-8" CXX_STANDARD=17
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'ppa:mhier/libboost-latest'
        - llvm-toolchain-trusty-8
        packages:
        - clang-8
        - g++-8
        - boost1.70
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-8" CXX_STANDARD=17 TOML_HEAD=ON
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'ppa:mhier/libboost-latest'
        - llvm-toolchain-trusty-8
        packages:
        - clang-8
        - g++-8
        - boost1.70
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-8" CXX_STANDARD=11 WITH_ASAN=ON
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'ppa:mhier/libboost-latest'
        - llvm-toolchain-trusty-8
        packages:
        - clang-8
        - g++-8
        - boost1.70
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-8" CXX_STANDARD=11 WITH_UBSAN=ON
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'ppa:mhier/libboost-latest'
        - llvm-toolchain-trusty-8
        packages:
        - clang-8
        - g++-8
        - boost1.70
  - os: osx
    language: cpp
    compiler: clang

script:
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    mkdir -p cmake
    travis_retry wget "https://github.com/Kitware/CMake/releases/download/v3.14.5/cmake-3.14.5-Linux-x86_64.tar.gz"
    tar xf cmake-3.14.5-Linux-x86_64.tar.gz -C cmake --strip-components=1
    export PATH=${TRAVIS_BUILD_DIR}/cmake/bin:${PATH}
  fi
- |
  if [[ "${CXX_STANDARD}" == "" ]]; then
      export CXX_STANDARD="11"
  fi
- |
  if [[ "${TOML_HEAD}" != "ON" ]]; then
    export TOML_HEAD="OFF"
  fi
- echo "TOML_HEAD = ${TOML_HEAD}"
- |
  if [[ "${WITH_ASAN}" != "ON" ]]; then
    export WITH_ASAN="OFF"
  fi
- echo "WITH_ASAN = ${WITH_ASAN}"
- |
  if [[ "${WITH_UBSAN}" != "ON" ]]; then
    export WITH_UBSAN="OFF"
  fi
- echo "WITH_UBSAN = ${WITH_UBSAN}"
- cmake --version
- mkdir build
- cd build
- echo "COMPILER     = ${COMPILER}"
- echo "CXX_STANDARD = ${CXX_STANDARD}"
- cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_CXX_STANDARD=$CXX_STANDARD -DTOML11_USE_UNRELEASED_TOML_FEATURES=${TOML_HEAD} -Dtoml11_TEST_WITH_ASAN=${WITH_ASAN} -Dtoml11_TEST_WITH_UBSAN=${WITH_UBSAN} ..
- make
- ctest --output-on-failure
